# Generated by Django 3.1.7 on 2021-03-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megahack2', '0003_auto_20210310_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='code_of_conduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'code_of_conduct',
                'verbose_name_plural': 'code_of_conducts',
            },
        ),
        migrations.CreateModel(
            name='rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'rule',
                'verbose_name_plural': 'rules',
            },
        ),
        migrations.CreateModel(
            name='view_poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'view_poster',
                'verbose_name_plural': 'view_poster',
            },
        ),
    ]
