# Generated by Django 3.1.7 on 2021-03-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megahack2', '0005_registration_four_registration_one_registration_three_registration_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration_five',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'registration_five',
                'verbose_name_plural': 'registration_five',
            },
        ),
    ]
