# Generated by Django 3.1.7 on 2021-03-10 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('megahack2', '0006_registration_five'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration_four',
            options={'verbose_name': 'registration_four', 'verbose_name_plural': 'registration_four'},
        ),
        migrations.AlterModelOptions(
            name='registration_one',
            options={'verbose_name': 'registration_one', 'verbose_name_plural': 'registration_one'},
        ),
        migrations.AlterModelOptions(
            name='registration_three',
            options={'verbose_name': 'registration_three', 'verbose_name_plural': 'registration_three'},
        ),
        migrations.AlterModelOptions(
            name='registration_two',
            options={'verbose_name': 'registration_two', 'verbose_name_plural': 'registration_two'},
        ),
    ]
