# Generated by Django 3.1.7 on 2021-03-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megahack2', '0007_auto_20210310_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='step_one',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'step_one',
                'verbose_name_plural': 'step_one',
            },
        ),
        migrations.CreateModel(
            name='step_three',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'step_three',
                'verbose_name_plural': 'step_three',
            },
        ),
        migrations.CreateModel(
            name='step_two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'step_two',
                'verbose_name_plural': 'step_two',
            },
        ),
    ]
